- .travis.yml
This PR fixes the Travis CI deployment by logging into GH + GHE using personal access tokens since public repos cannot use SSH keys in Travis. See https://stackoverflow.com/a/51092120 and https://docs.travis-ci.com/user/private-dependencies#api-token for more details.
[Travis build logs](https://app.travis-ci.com/github/IBM/detect-secrets/jobs/531767561):
```
git fetch origin --tag
TAG_VERSION=$(git describe --tags --abbrev=0); \
NEW_VERSION=$(grep VERSION detect_secrets/__init__.py | cut -d\' -f2 ); \
if [ $TAG_VERSION != $NEW_VERSION ]; then \
git tag $NEW_VERSION 6622c0d2ddf3e6663ccc97fac41b691a972fcf4e; \
git push origin --tags; \
fi
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/IBM/detect-secrets.git/'
Makefile.ibm:106: recipe for target …
```
> Login to GH and GHE to fix deploy

- .travis.yml
See https://docs.travis-ci.com/user/ssh-known-hosts/
Fixes
```
git fetch github
The authenticity of host 'github.ibm.com (169.60.70.162)' can't be established.
...
Are you sure you want to continue connecting (yes/no)? 
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
The build has been terminated
```
> Fix GHE host authenticity issue with Travis build

- detect_secrets/core/usage.py
- detect_secrets/plugins/github_enterprise.py
- detect_secrets/plugins/github_token.py
- tests/plugins/gh_enterprise_test.py
- tests/plugins/github_token_test.py
Changes:
- Adding github token detector from yelp's upstream
- Plugin: https://github.com/Yelp/detect-secrets/blob/master/detect_secrets/plugins/github_token.py
- Tests: https://github.com/Yelp/detect-secrets/blob/master/tests/plugins/github_token_test.py
- Updated previous GHE plugin to be more specific that its a Github Enterprise credential 
- Renamed file from `gh` to `github_enterprise`
- Update help text 
- Updated secret_type
> Adding github token detector from yelp's upstream

- .secrets.baseline
- docs/audit.md
- docs/developer-tool-faq.md
Internal issue #667
- Adding audit doc from upstream https://github.com/Yelp/detect-secrets/blob/master/docs/audit.md
- Making it clear when marking a potential secret as a valid secret, that the user is expected to remediate the token
- Linked/added this question to FAQ page 
Overall, trying to consolidate audit documentation into a single file so users wont have to look around in multiple places
> adding audit documentation

- .secrets.baseline
- docs/audit.md
Changes to audit documentation:
- Add table of contents
- Update link to use relative path instead of absolute path
> Add table of contents to audit documentation

- tests/plugins/ibm_cloud_iam_test.py
With the latest requests package version 2.27.0 made the following change:
```
- Added a `requests.exceptions.JSONDecodeError` to unify JSON exceptions between
Python 2 and 3. This gets raised in the `response.json()` method, and is
backwards compatible as it inherits from previously thrown exceptions.
Can be caught from `requests.exceptions.RequestException` as well. (5856)
```
See https://pyup.io/changelogs/requests/ for more changes
Because of this we are swallowing the `RequestException` and returning `VerifiedResult.UNVERIFIED`. See https://github.com/IBM/detect-secrets/blob/master/detect_secrets/plugins/ibm_cloud_iam.py#L40
Changes: 
- Fixing IBM Cloud IAM test: test_verify_payload_not_json
> resolving IBM Cloud IAM test test_verify_payload_not_json

- detect_secrets/core/baseline.py
- detect_secrets/core/secrets_collection.py
When running on Windows natively, write baseline files using forward-slash path separators, for cross-platform compatibility.
Without this, entries created from other platforms can be mismatched by `detect secrets audit`, and it becomes impossible to pass the pre-commit check.
After:
```
$ detect-secrets scan
{
// ... snipped ...
],
"results": {
"docs/_how-to/API-keys.md": [
{
"hashed_secret": "bf10dae7b89461df3fd3c48f86ec23543710e8cd",
"is_verified": false,
"line_number": 194,
"type": "Secret Keyword",
"verified_result": null
},
```
Before:
```
$ detect-secrets scan
{
// ... snipped ...
],
"results": {
"docs\\_how-to\\API-keys.md": [
{
"hashed_secret": "bf10dae7b89461df3fd3c48f86ec23543710e8cd",
"is_verified": false,
"line_number": 194,
"type": "Secret Keyword",
"verified_result": null …
```
> Windows native: always use forward-slash path separators

- detect_secrets/core/usage.py
Supports internal issue 623 in Team-backlog
This is a sub-PR of https://github.com/IBM/detect-secrets/pull/46 (I'm breaking down the reporting PR for easier readability for reviewers).
- Formatted `usage.py`
- Added reporting feature arguments using [`argparse`](https://docs.python.org/3/library/argparse.html) module
- Overwrote detect-secrets audit usage string. The reason why it needs to be overwritten is because `argparse` does not support mutually inclusive args by default - example use case: `--fail-on-xx` should only be used when `--report` is included.
- Needed to write custom validation logic for mutually-inclusive args (will open future PR for this): https://github.com/victoria-miltcheva/detect-secrets/blob/report/detect_secrets/core/report/report.py#L106-L139
Command: …
> Add usage for reporting functionality

- detect_secrets/core/usage.py
- detect_secrets/pre_commit_hook.py
- docs/cheat-sheet.md
- tests/pre_commit_hook_test.py
- user-config/.pre-commit-config.yaml
Supports internal issue 623 in Team-backlog
This is a sub-PR of https://github.com/IBM/detect-secrets/pull/46 (I'm breaking down the reporting PR for easier readability for reviewers).
This PR refactors the `--fail-on-non-audited` pre-commit hook argument to `--fail-on-unaudited`. In the new reporting feature, one of the fail-on arguments will be `--fail-on-unaudited`, so it wouldn't make sense to have a pre-existing argument which conflicts with this name. Also, since the word `unaudited` is the correct dictionary spelling, I am opting to go with this naming convention. 
As a result of this change, users who are using `--fail-on-non-audited` in the pre-commit config files will need to use the updated argument name instead. I will include this breaking change in the announcement that will …
> Rename --fail-on-non-audited to --fail-on-unaudited for pre-commit hook

- detect_secrets/core/audit.py
- detect_secrets/core/report/conditions.py
- detect_secrets/core/report/constants.py
- testing/baseline.py
- tests/core/report/conditions_test.py
Supports internal issue 623 in Team-backlog
This is a sub-PR of https://github.com/IBM/detect-secrets/pull/46 (I'm breaking down the reporting PR for easier readability for reviewers).
- Added `get_secrets_list_from_file` to `audit.py`. This makes it simpler to extract a list of secrets from a baseline file. To be used by fail on functions to get secrets list, as well as for getting secrets information for the report console output.
- Added `conditions.py` to a reporting directory under `detect-secrets/core`. The functions within this file correspond to the report `fail-on-xx` CLI arguments.
- Added a `constants.py` file which contains exit report exit code and secret type enums ~as well as custom types~.
- Added a `conditions_test.py` file which contains various tests for the `fail-on` …
> Add fail-on functions, tests, and constants for reporting module

- detect_secrets/core/report/report.py
- detect_secrets/core/usage.py
- detect_secrets/main.py
- tests/core/report/report_test.py
Supports internal issue 623 in Team-backlog
This is a sub-PR of https://github.com/IBM/detect-secrets/pull/46 (I'm breaking down the reporting PR for easier readability for reviewers).
- Adds `report.py`, which serves as the entrypoint for the audit reporting functionality.
- Adds report.py execute function to `main.py`, so reporting can now be used.
- Adds tests for reporting
- `usage.py`: moves filename argument to end, updates usage string to be more readable.
> Add reporting entrypoint file and its tests, and link it to main

- detect_secrets/core/report/output.py
- tests/core/report/output_test.py
Fixes `detect-secrets audit --report --omit-instructions .secrets.baseline` output. In the case where the `--omit-instructions` argument is included and there are secret results which fail conditions, additional newlines are included in the output, making it inconsistent with the rest of the reporting output cases.
So this:
```
$ detect-secrets audit --report --omit-instructions .secrets.baseline
10 potential secrets in .secrets.baseline were reviewed. Found 1 live secret, 1 unaudited secret, and 1 secret that was audited as real.
Failed Condition    Secret Type              Filename                                 Line
------------------  -----------------------  -------------------------------------  ------
Live                Hex High Entropy String  docs/audit.md …
```
> Don't include unnecessary newlines when omitting report output instructions

- Dockerfiles/detect-secrets-redhat-ubi/00.python-redhat-ubi.Dockerfile
Starting with the Redhat ubi:python-39  UBI image, run the yum update to update the packages.  ie grab updates to get any fixed vulnerabilities fixes.
> add yum update to container

- detect_secrets/core/report/output.py
- docs/audit.md
- tests/core/report/output_test.py
Fixes the following output:
```
10 potential secrets in .secrets.baseline were reviewed. Found and 1 secret that was audited as real.
Failed Condition    Secret Type    Filename                                 Line
------------------  -------------  -------------------------------------  ------
Audited as real     Private Key    detect_secrets/plugins/private_key.py      45
Failed conditions:
- Audited true secrets were found
Remove secrets meeting this condition from the codebase, and run detect-secrets scan --update .secrets.baseline to re-scan.
For additional help, run detect-secrets audit --help.
```
```
10 potential secrets in .secrets.baseline were reviewed. Found 1 secret that was audited as real.
Failed Condition    Secret Type    Filename                                 Line …
```
> Fix inconsistencies with fail-on stats text output

- detect_secrets/core/report/output.py
- tests/core/report/output_test.py
Before:
```
$ detect-secrets audit --report .secrets.baseline
10 potential secrets in .secrets.baseline were reviewed. Found 1 live secret, 1 unaudited secret and 1 secret that was audited as real.
Failed Condition    Secret Type              Filename                                 Line
------------------  -----------------------  -------------------------------------  ------
Live                Hex High Entropy String  docs/scan.md                               49
Unaudited           Private Key              detect_secrets/plugins/private_key.py      51
Audited as real     Private Key              detect_secrets/plugins/private_key.py      50
Failed conditions:
- Unaudited secrets were found
Run detect-secrets audit .secrets.baseline, and audit all potential secrets.
- Live secrets were …
```
> Fix reporting spacing

- detect_secrets/core/audit.py
Before:
```
$ detect-secrets audit --report --fail-on-unaudited nonexisting.baseline
Not a valid baseline file!
Traceback (most recent call last):
File "/Users/vmiltche/.pyenv/versions/3.8.9/bin/detect-secrets", line 33, in <module>
sys.exit(load_entry_point('detect-secrets==0.13.1+ibm.47.dss', 'console_scripts', 'detect-secrets')())
File "/Users/vmiltche/.pyenv/versions/3.8.9/lib/python3.8/site-packages/detect_secrets/main.py", line 78, in main
report.execute(args)
File "/Users/vmiltche/.pyenv/versions/3.8.9/lib/python3.8/site-packages/detect_secrets/core/report/report.py", line 54, in execute
(unaudited_return_code, unaudited_secrets) = fail_on_unaudited(
File "/Users/vmiltche/.pyenv/versions/3.8.9/lib/python3.8/site-packages/detect_secrets/core/report/conditions.py", line 15, in …
```
> Fix baseline not found and invalid baseline format error handling

- Dockerfiles/detect-secrets-redhat-ubi/01.detect-secrets-redhat-ubi.Dockerfile
- Dockerfiles/detect-secrets-redhat-ubi/02.detect-secrets-redhat-ubi-custom.Dockerfile
- Dockerfiles/detect-secrets-redhat-ubi/02.detect-secrets-redhat-ubi.Dockerfile
- Makefile.ibm
- scripts/run-in-pipeline.sh
expose 2 redhat ubi containers  
- one with custom script entry point 
- one with direct detect-secrets entry point.
detect-secrets-redhat-ubi-custom
```
tefiggins@tefigginss-MacBook-Pro detect-secrets % docker run  -it -a stdout --rm -v $(pwd):/code --env BASELINE=timtest.baseline  --env FAIL-ON-UNAUDITED=TRUE   git-defenders/detect-secrets-redhat-ubi-custom  
[ Starting Detect Secrets run ]
...using baseline: timtest.baseline
...skip scan with baseline update: false
...output json: false
...omit instructions: false
...fail on live: true
...fail on unaudited: true
...fail on audited real: true
Scanning code directory (docker volume mounted to /code) and updating baseline file timtest.baseline ... 
Running report: Baseline timtest.baseline - Options:  --fail-on-live --fail-on-unaudited …
```
> expose 2 redhat ubi containers  

- Makefile.ibm
For issue:  Whitewater/whitewater-detect-secrets#489
We currently publish Detect Secrets Docker images to both internal Artifactory and DockerHub. We should additionally be publishing to the IBM public container registry.
It's fine to continue publishing to DockerHub since our external users can use this.
> Push to ICR as well

- Dockerfiles/base/00.python-redhat-ubi.Dockerfile
- Dockerfiles/detect-secrets/01.detect-secrets-redhat-ubi.Dockerfile
For pipelines the desire is to have all containers base on UBI. Detect Secrets is a python project and thus we use the python39 tagged UBI image. Once pushed to ICR, ICR scans showed some config issues with mysql and apache (note: we don't use either).
The PR is to redo the DS UBI containers and start with UBI-minimal and add python38 (ALSO going to python38 since the one with auto UT testcases) and git (used by scan process) to the image. Thus having the most minimalistic container necessary to run the Detect Secrets scans and reporting.
Note UBI-minimal does not have yum command like UBI-standard-- must use: microdnf command
> Base on UBI minimal image with python38 added vs python39 UBI

- Makefile.ibm
This PR will address both powerups backlog issue 755 and 490.
- Fix detect-secrets Docker image tagging in Makefile to include additional tags (755)
> A previous PR modified the way the `docker-publish-iamges` make target worked, but it also lost the debug tagged images and some other specific tagged images that we think it needed.   This PR addresses this issue.
- Build and publish versioned images for detect-secrets:redhat-ubi and detect-secrets:redhat-ubi-custom (490)
> There's currently no way for our users to pull down a specific version of the detect-secrets redhat-ubi-tagged images. This is fine for now, but when we release the next version of Detect Secrets, our users will get that most recent image version since there's no way to peg to a specific version for these images. This …
> Fix detect-secret tagging and also publish versioned UBI-images

- docs/audit.md
Information Update:  Users can reference a specific version of the detect-secrets redhat-ubi-tagged images.
> Update Doc for image Versioning

- .github/workflows/codeql-analysis.yml
- .travis.yml
- Makefile.ibm
- requirements-dev.txt
- tox.ini
Replaces `safety` check with `trivy`'s filesystem vulnerability scan. Trivy will detect a Pip package lockfile, which we generate via a script. We have to do this because Trivy does not auto-detect `requirements-dev.txt` (see https://aquasecurity.github.io/trivy/v0.28.1/docs/vulnerability/detection/language/ for a list of auto-detected language-specific files).
Also fixes pre-commit errors with `.github/workflows/codeql-analysis.yml`.
> Replace safety check with Trivy Python package scan

- .pre-commit-config.yaml
- .secrets.baseline
- detect_secrets/__init__.py
- detect_secrets/core/baseline.py
- detect_secrets/core/report/conditions.py
- detect_secrets/core/report/output.py
- detect_secrets/pre_commit_hook.py
- docs/audit.md
- docs/cheat-sheet.md
- tests/core/report/output_test.py
- tests/pre_commit_hook_test.py
**Description**
- Reporting: updates the `--fail-on-unaudited` remediation instructions to be more specific.
- Adds a `--fail-on-unaudited` flag to this repo's pre-commit config file. This prevents unaudited secrets from being committed.
- Bumps the developer tool version used in the pre-commit config file, so that it recognizes the `--fail-on-unaudited` option.
- Updates this repo's baseline file.
- Fixes documentation references: non-audited -> unaudited.
- Updates documentation examples for the `--fail-on-unaudited` report output.
- Bumps release version
**Report output changes**
Only unaudited secrets found:
```
10 potential secrets in .secrets.baseline were reviewed. Found 1 unaudited secret.
Failed Condition    Secret Type    Filename                                 Line …
```
> Report wording update: --fail-on-unaudited

- docs/developer-tool-faq.md
I did try to use detect-secret and exclude my package-lock.json file . However, that command did not help me achieve that as it was missing `--update` flag. After talking to the team, I realized I need to add that flag to the command and thus creating a PR which has the flag updated in sh command and also an example that can help adopters know how to easily exclude files while using detect-secret.
> adding example for exclude-files in developer-tool-faq.md

- Dockerfiles/base/00.python.Dockerfile
- Dockerfiles/base/01.cli.Dockerfile
I think these are the `Dockerfile`s for an image that I use a lot and that is pulled a lot. And I saw that one of those images comes with a lot of layers, so I had a look.
To the best of my knowledge, there is no real penalty to lots of layers in container images anymore. Still, a lot of smaller layers can make a overall pull operation slower on average.
Therefore, I had a look and think we can tweak at least the layers that we contribute in the respective `Dockerfile`s. It is basically putting together commands that belong together anyway, plus removing the README file from the image as I believe nobody will probably read it in there. What do you think?
> Tweak base Dockerfiles

- .pre-commit-config.yaml
- .secrets.baseline
- .travis.yml
- Makefile.ibm
- requirements-dev.txt
- tests/util_test.py
- user-config/detect-secrets.psm1
IBMCOM is being removed from DockerHub. This removes references to the DockerHub image of Detect Secrets, replacing it with references to IBM's ICR. 
* Updates vulnerable package
> Removing dockerhub references

- user-config/.pre-commit-config.yaml
This PR migrates the detect secrets pre-commit config intended for users.
Resolves this warning:
```
> pre-commit install
[WARNING] normalizing pre-commit configuration to a top-level map. support for top level list will be removed in a future version. run: `pre-commit migrate-config` to automatically fix this.
[WARNING] The 'rev' field of repo 'https://github.com/ibm/detect-secrets' appears to be a mutable reference (moving tag / branch). Mutable references are never updated after first install and are not supported. See https://pre-commit.com/#using-the-latest-version-for-a-repository for more details. Hint: `pre-commit autoupdate` often fixes this.
pre-commit installed at .git/hooks/pre-commit
```
> pre-commit migrate-config

- .pre-commit-config.yaml
- .secrets.baseline
- update.md
- user-config/.pre-commit-config.yaml
Using a branch name as the pre-commit config `rev` such as `master` isn’t supported by [pre-commit](https://pre-commit.com/). I ran `pre-commit autoupdate`, which is the solution recommended by `pre-commit`.
This is the warning I get when using the pre-commit config from our codebase (note that it’s using a super old version of DS):
```
[WARNING] The 'rev' field of repo 'https://github.com/ibm/detect-secrets' appears to be a mutable reference (moving tag / branch).  Mutable references are never updated after first install and are not supported.  See https://pre-commit.com/#using-the-latest-version-for-a-repository for more details.  Hint: `pre-commit autoupdate` often fixes this.
Detect secrets...........................................................Failed
- hook id: detect-secrets
- …
```
> Use latest version tag rather than branch name for user pre-commit file rev

- Makefile.ibm
Fixes this error:
```bash
/bin/bash: line 1: /tmp/cosign: Permission denied
```
> Make /tmp/cosign executable

- detect_secrets/__init__.py
- requirements-dev.txt
- setup.py
Since the `requests` `v2.30.0` package appears to be broken, I've pegged `requests` to the previous version. I've also bumped the version of `urllib3` used for local development to the version which comes with `requests` `v2.29.0`.
> Peg requests (new version is broken), and update urllib3 in requirements-dev

- .secrets.baseline
- detect_secrets/__init__.py
- requirements-dev.txt
- setup.py
- user-config/.pre-commit-config.yaml
Unpins the requests dependency, but adds a pinned urllib3 dependency. Upstream requests says ["this isn't a requests problem, its a how you're getting urllib3 problem"](https://github.com/psf/requests/issues/6443); Also - [CVE-2023-32681](https://github.com/advisories/GHSA-j8r2-6x86-q33q) is getting flagged in requests < 2.31.0, so hopefully this would resolve that, as well.
From a fresh python 3.9.16 venv via direnv:
```bash
export PYENV_VERSION=3.9.16
layout python3
```
Then
```bash
which detect-secrets
detect-secrets not found
pip install --upgrade "git+https://github.com/bigpick/detect-secrets.git@unpin-requests-dep#egg=detect-secrets"
detect-secrets --version
0.13.1+ibm.61.dss
detect-secrets scan --update .secrets.baseline --use-all-plugins .
echo $?
0
detect-secrets audit …
```
> chore: Unpin requests dep, pin urllib3 dep

- .travis.yml
- detect_secrets/__init__.py
- detect_secrets/core/usage.py
- detect_secrets/main.py
- detect_secrets/pre_commit_hook.py
- detect_secrets/util.py
- tox.ini
Skip the remote version check (to s3) if the user passes `--no-version-check` as a cmdline option.
Fixes IBM/detect-secrets#42
> feat: add `--no-version-check` cmdline option

- Makefile.ibm
- docs/developer-tool-faq.md
- trivy-secret.yaml
Update docs to remove references to docker desktop and add links to rancher desktop and podman desktop
> Update docs to remove references to docker desktop

- Makefile.ibm
- tests/core/baseline_test.py
- tests/core/secrets_collection_test.py
- tests/plugins/aws_key_test.py
- tests/plugins/common/initialize_test.py
- tests/plugins/high_entropy_strings_test.py
Update makefile to solely push images to ICR rather than ICR and Artifactory
> Update makefile to remove Artifactory references
